name: Convert BT Trackers to Clash Rules

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run conversion script
        run: python3 'auto phrase.py'  # This runs the script you created

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add clash_bt_trackers.list
          git commit -m "Update Clash BT tracker rules" || echo "No changes to commit"
          git pull --rebase  # Pull the latest changes before pushing
          git push origin main  # Push changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use GitHub's built-in token
